#!/bin/sh

run() {
    $HADOOP jar $HADOOP_JAR \
      -D $TOOLRUNNER_OPTIONS \
      -file lib/$MAPPER -mapper $MAPPER \
      -file lib/$REDUCER -reducer $REDUCER \
      -input $INFILE -output $HDFS_OUT
}

run $*
