#!/bin/sh

run() {
    $HADOOP jar $HADOOP_JAR \
      -D $TOOLRUNNER_OPTIONS \
      -file lib/$MAPPER -mapper $MAPPER \
      -file lib/$REDUCER -reducer $REDUCER \
      -input $HDFS_IN/* -output $HDFS_OUT \
      -file lib/cached.rb
}

run $*
